#!/bin/bash
cat >Dockerfile <<EOF
FROM ubuntu:quantal
MAINTAINER marksteve
RUN apt-get -y install wget
RUN wget -q -O - http://apt.mopidy.com/mopidy.gpg | apt-key add -
RUN wget -q -O /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list
RUN apt-get -q update
RUN apt-get -y install mopidy
RUN apt-get -y install python-setuptools
RUN easy_install cherrypy>=3.2.2
RUN echo $(getent passwd $(id -u)) >> /etc/passwd
RUN echo $(getent group $(id -g)) >> /etc/group
RUN adduser $USER audio
RUN mkdir $HOME
RUN chown $(id -u -n):$(id -g -n) $HOME
RUN mkdir /var/media
RUN chown -R $(id -u -n):$(id -g -n) /var/media
WORKDIR $HOME
ENV HOME $HOME
USER $USER
ENTRYPOINT ["mopidy"]
EOF
sudo docker build -t mopidy -rm .
