#!/bin/bash
sudo docker run -t -i -rm \
  -v `pwd`:/var/media \
  -v /dev/snd:/dev/snd \
  -lxc-conf='lxc.cgroup.devices.allow = c 116:* rwm' \
  -p 6600:6600 \
  -p 6680:6680 \
  -h mopidy \
  -volumes-from mopidy-volume \
  --name mopidy \
  marksteve/mopidy $@
