FROM marksteve/base
RUN apt-add-repository -y ppa:fkrull/deadsnakes
RUN apt-get update
RUN apt-get -y install python2.6 python2.6-dev
ADD https://raw.github.com/pypa/pip/master/contrib/get-pip.py /tmp/get-pip.py
RUN python2.6 /tmp/get-pip.py

