#!/bin/bash
mysqld_safe &

# Wait for MySQL server sto start
while true; do
  echo "Waiting for MySQL server to start..."
  mysqladmin ping >/dev/null 2>&1 && break
  sleep 0.5
done

# Setup system tables
mysql_install_db >/dev/null 2>&1 && echo "Installed system tables"

# Execute /tmp/setup.sql
mysql -uroot < /tmp/setup.sql  && echo "Executed /tmp/setup.sql"

# Shut down
mysqladmin shutdown
